class ErrorsException < RangeError  
  def self.with_errors(errors)
      
  end  
  
end